### ISSUE TITLE
Encryption message is not treated as a system message

### ISSUE THREAD

**Issue by PKehnel** [Pustur/whatsapp-chat-parser-website#3]
![groupChat](https://user-images.githubusercontent.com/23440847/110303280-82539780-7ffa-11eb-8151-ccdbd0862675.png)

Export Group is the name of the group. 
Guess this happens for "recently created" groups. 

first lines of txt:

```
[04.03.21, 10:18:18] ‎You created group “Export group”
[04.03.21, 10:18:18] Export group: ‎Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.
‎[04.03.21, 10:18:30] Adrian: ‎<attached: 00000002-PHOTO-2021-03-04-10-18-29.jpg>
‎[04.03.21, 10:18:39] Adrian: ‎<attached: 00000003-VIDEO-2021-03-04-10-18-38.mp4>
```

**Comment by Pustur** [comment]
Hello,

What's the issue you're describing here?

If you mean that the message about the end-to-end encryption should not have an "author" and thus be treated as a system message, I'm afraid I can't do much about it since it's whatsapp that decides to use this format.

**Comment by PKehnel** [comment]
in the whatsapp view, messages from the group itself, are styled like system messages.
![Screenshot_20210308-174850](https://user-images.githubusercontent.com/23440847/110352866-ba78cb80-8036-11eb-8179-611f49362e05.png)

**Comment by Pustur** [comment]
Ok thanks for the clarification.

Unfortunately as I said before this is a problem with how whatsapp exports the chat.  
It automatically adds the author (in this case the group name) and my app can't tell that it's a system message.

I'm closing this as I don't want to make a special rule for this case (it would be an ugly hack)

**Comment by PKehnel** [comment]
I think you could filter the message, as the chat name normally equals the .txt name, but as you like. 
Also think it's important, as this is the first impression people have from your application.

**Comment by Pustur** [comment]
Ok I decided to add a quick check.
If the string `end-to-end` is found in the first 10 messages, that message will have the author set to `System`.

This does not cover all cases, but should be good for most.

You can test it here:
https://60466ad559ccd900070f83d0--whatsapp-chat-parser.netlify.app/

I'll release a new version when you confirm this issue as well as #4 are fixed.

**Comment by PKehnel** [comment]
end-to-end will only cover the english systems, but jeah fixes the issue.

**Comment by Pustur** [comment]
> end-to-end will only cover the english systems, but jeah fixes the issue.

It actually covers quite a bit of languages, here are some samples:

Italian 🇮🇹
> I messaggi inviati a questa chat e le chiamate sono ora protetti con la crittografia **end-to-end**.

English 🇺🇸
> Messages to this group are now secured with **end-to-end** encryption.

Indonesian 🇮🇩
> Pesan yang dikirim ke grup ini kini diamankan dengan enkripsi **end-to-end**. Ketuk untuk info selengkapnya.

Dutch 🇳🇱
> Berichten die naar deze groep worden verzonden, zijn nu beveiligd met **end-to-end** encryptie.
