### ISSUE TITLE
message replies (quotes)

### ISSUE THREAD

**Issue by kintaro1981** [Pustur/whatsapp-chat-parser-website#31]
how about to support message quotes?
do you think it's feasible?

**Comment by kintaro1981** [comment]
Yes I mean that.

I think that the only way is export from wa’s db. 😞 

I found KnugiHK/Whatsapp-Chat-Exporter can do it but for replies supports only Android’s db.

**Comment by Pustur** [comment]
I'll close this for now since it's currently impossible without thinkering with whatsapp's internal DB, and this project is only intended to work with the export feature of the app.
