### ISSUE TITLE
Voice messages not playing

### ISSUE THREAD

**Issue by fabiogelbcke** [Pustur/whatsapp-chat-parser-website#32]
Hi, first of all, thanks for this tool, I was really in need of something like this, and really happy to find it.

The issue I'm having is that it doesn't seem to be loading the voice message files correctly. All my voice messages appear as an audio player with the message "Error".

<img width="405" alt="Screenshot 2023-12-20 at 1 35 08 PM" src="https://github.com/Pustur/whatsapp-chat-parser-website/assets/5251445/fd1b7042-3f77-486d-a37f-f2b7afb5b560">

I'm uploading the chat from a zip file, and I've verified that the audio files for the voice messages are present in .opus format. I don't have any errors or messages on my console. Other media (at least photos and videos) seems to work fine.

**Comment by Pustur** [comment]
Hi, I just tried to export a chat with 5 audio clips (in `.opus` format as well) and all worked fine in my case.

Can I ask you what OS and Browser are you using?
Are there any options that could be useful when you right click the audio player?

**Comment by fabiogelbcke** [comment]
Thanks for the quick response :)

I was trying Safari on iOS and MacOS and it wasn't working, but I just tried on Chrome on MacOS and it does seem to work, so maybe the audio player on safari doesn't support .opus or something like that.

**Comment by Pustur** [comment]
Yes, as shown in https://caniuse.com/opus, safari has a hard time with this format. Nothing I can do about it unfortunately, closing.
