### ISSUE TITLE
Emoji's not rendering for old (2013) chats?

### ISSUE THREAD

**Issue by JoeSlab** [Pustur/whatsapp-chat-parser-website#34]
I want to start by saying this chat parser is really great. I wanted to export some really old chats from 2012-2018 and render them as seen on the phone.
Most (but not all) of the emojis in these chats are rendering as a white box with eg E405
![E405_winkingface](https://github.com/Pustur/whatsapp-chat-parser-website/assets/168724310/6e4a379a-8803-4956-b458-34e7cf16258e)
E405 is winking face: https://www.iemoji.com/view/emoji/5/smileys-people/winking-face
I'm using firefox, and the identical winking face emoji from very recent exported chats renders correctly - now I believe the winking face is F609?
Is there any way of making these older emojis from older chats render correctly? Many thanks.

**Comment by Pustur** [comment]
Hi @JoeSlab 

I believe that the code for some emojis have changed over the years which results in the problem you're seeing. I don't think this is in any way related to my program but instead how the chat was originally saved.

As for the solution, the only one I can think of would be to do a search and replace whenever you see a missing emoji, but that could take a while. Maybe there are some programs out there for this but I don't know any.

Best of luck in restoring your chat

**Comment by JoeSlab** [comment]
Hi @Pustur 

Thank you very much for replying - I read that the emoji codes have changed over the years, but I didn't quite grasp how that make this a hard problem to solve! Yes of course - I should have checked the text file, and as expected all the modern emojis render correctly and the older ones don't - so yes it's definately not the fault of your program. I may try a find and replace, at least for the more popular smileys - thanks for the suggestion.  Thanks again for a great piece of software ;-)
