### ISSUE TITLE
Scrambling phone numbers and names from the displayed webpage

### ISSUE THREAD

**Issue by alpentmilch** [Pustur/whatsapp-chat-parser-website#36]
We usually archive one of our chat groups where we share recipes. To prevent any *inadvertent* leak I would like to keep those [html files ](https://github.com/Pustur/whatsapp-chat-parser-website/issues/17#issuecomment-1135476373) with anonymous numbers.

(BTW, this tool is really great. Kudos)

**Comment by Pustur** [comment]
Hi @alpentmilch 

I'll consider adding an option for that whenever I have time

**Comment by Pustur** [comment]
@alpentmilch Added this feature in the menu once you load a chat log, can you test if everything works fine?
I'll push this change to the real domain in about 2 weeks when i return from a vacation
