### ISSUE TITLE
Dokumentation - maybe

### ISSUE THREAD

**Issue by detlefm** [Pustur/whatsapp-chat-parser-website#45]
paudio.py runs as expected. But I can't get the web interface to work.
The README does not describe whether I should install additional libraries for npm.
Anyway, npm start in the frontend directory brings the following error message:

npm start                                           
> creator-front-end@0.1.0 start
> react-scripts start
The command “react-scripts” is either misspelled or could not be found.

Since I have no idea about react I need help here. node and npm are up to date.

**Comment by Pustur** [comment]
You opened the issue in the wrong repo... now read the readme again and hopefully you can get it to run

**Comment by detlefm** [comment]
Sorry for my confusion. I was too inattentive and ended up in the wrong repository.
