### ISSUE TITLE
how to manually choose the author

### ISSUE THREAD

**Issue by kintaro1981** [Pustur/whatsapp-chat-parser-website#7]
Hello,
I tried to use it with some exported group chats but it seams to "randomly" chose who is the author (green bubble).
Is it possibile to set in the code or in the GUI who is the author?

**Comment by Pustur** [comment]
Hello,

No at the moment it's not possible to assign a custom author.  
I'll consider adding it in the future.

**Comment by Pustur** [comment]
Well, the future is now 😎

New version `1.7.0` is live and has this feature in the sidebar.

@PKehnel I think you requested this as well.

I'm closing the issue for now, but feel free to comment if something is not working as expected.

**Comment by kintaro1981** [comment]
Works like a charm.
Thank you.
